te = input('Escreva algo: ')
print('O tipo primitivo desse valor é ', type(te))
print('Isso é um Alpha númerico?', te.isalnum())
print('Está em minusculo?', te.islower())
print('Esta em maiúsculo', te.isupper())
print('É um número?', te.isnumeric())
print('É um número decimal?', te.isdecimal())
print('Consegue visualizar oque escreveu?', te.isprintable())
print('não escreveu nada?', te.isspace())
print('é uma letra?', te.isalpha())
print('está capitalizada?', te.istitle())
